import {Component} from "react";
import Head from "next/head";
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/components/Header.module.scss';
import {Header} from "../models/common";

class HeaderComponent extends Component<Header>{
    render() {
        return (
            <>
                <Head>
                    <title>{this.props.title}</title>
                    <meta name="description" content="Generated by create next app"/>
                </Head>
                <header className={styles.heading}>
                    <Image
                        alt={'Midwestern Interactive Logo'}
                        src={'/images/Logo.svg'}
                        height={75}
                        width={350}
                    />
                    <Link href={this.props.link.url}>
                        <a >{this.props.link.text}</a>
                    </Link>

                </header>
            </>
        )
    }
}

export default HeaderComponent
