import { useState } from 'react'
import {InferGetStaticPropsType} from "next";
import {CardData} from "../models/common";
import Head from "next/head";
import Card from "../components/card";
import styles from '../styles/pages/Landing.module.scss'

type LandingViewModel = {
    title: string
    cards?: CardData[]
}

const Landing = ( {content} : InferGetStaticPropsType<typeof getStaticProps> ) => {
    const [filteredNames, setFilteredNames] = useState<string[]>()

    function filterDuplicateNamesChallenge(){
        let firstList = [
            'Matt Johnson',
            'Bart Paden',
            'Ryan Doss',
            'Jared Malcolm'
        ];
        let secondList = [
            'Matt Johnson',
            'Bart Paden',
            'Jordan Heigle',
            'Tyler Viles'
        ];

        let combinedList = secondList.concat(firstList);
        setFilteredNames(combinedList
            .filter((object, index, array) => array.findIndex(o => o == object) === index
        ));
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>{content.title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>
                {content.cards?.map((card, index) => {
                    return (
                        <Card key={index}
                              icon={card.icon}
                              heading={card.heading}
                              body={card.body}
                              button={card.button}
                        />
                    )
                })}

                <div className={"challenge"}>
                    <button onClick={filterDuplicateNamesChallenge}>
                        Filter Names
                    </button>

                    <ul>
                        {filteredNames?.map( (name, index) =>
                            <li key={index}>{name}</li>
                        )}
                    </ul>
                </div>
            </main>
        </div>
    )
}

export const getStaticProps = async () => {
    const content: LandingViewModel = {
        title: "Landing",
        cards: [
            {
                heading: "Heading One",
                body: "Integer accumsan molestie nisl, id faucibus urna accumsan quis. Proin vulputate, mauris semper maximus. ",
                button: {
                    text: "Learn More",
                    url: "https://github.com/Midwestern-Interactive/tech-challenge"
                }
            },
            {
                heading: "Heading Two",
                body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore",
                button: {
                    text: "Learn More",
                    url: "https://github.com/Midwestern-Interactive/tech-challenge"
                }
            },
            {
                heading: "Heading Three",
                body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore",
                button: {
                    text: "Learn More",
                    url: "https://github.com/Midwestern-Interactive/tech-challenge"
                }
            }
        ]
    }

    return {
        props: {
            content
        }
    }
}

export default Landing
