import type { InferGetStaticPropsType } from 'next'
import { Card } from '../models/common'
import { ChallengeObject } from "../models/challenge";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type HomeViewModel = {
  title: string
  cards?: Card[]
  challenge: ChallengeObject[]
}

const Home = ( { content } : InferGetStaticPropsType<typeof getStaticProps> ) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{content.title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {content.cards?.map((card, index) =>
              <a key={index} href={card.url} className={styles.card}>
                <h2>{card.heading} &rarr;</h2>
                <p>{card.body}</p>
              </a>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const content: HomeViewModel = {
    title: "Midwestern Tech Challenge",
    cards: [
      { heading: "Documentation", body: "Find in-depth information about Next.js features and API.", url: "https://nextjs.org/docs"},
      { heading: "Learn", body: "Learn about Next.js in an interactive course with quizzes!", url: "https://nextjs.org/learn"},
      { heading: "Examples", body: "Discover and deploy boilerplate example Next.js projects.", url: "https://github.com/vercel/next.js/tree/master/examples"},
      { heading: "Deploy", body: "Instantly deploy your Next.js site to a public URL with Vercel.", url: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"},
    ],
    challenge: [
      {
        names: [
            'Matt Johnson',
            'Bart Paden',
            'Ryan Doss',
            'Jared Malcolm'
        ]
      },
      {
        names: [
          'Matt Johnson',
          'Bart Paden',
          'Jordan Heigle',
          'Tyler Viles'
        ]
      }
    ]
  }

  return {
    props: {
      content
    }
  }
}

export default Home
